include(InstallRequiredSystemLibraries)

install(TARGETS bubble_sort)
install(TARGETS bubble_sort_test)

set(CPACK_PACKAGE_CONTACT super@student.bmstu.ru)
set(CPACK_PACKAGE_VERSION_MAJOR ${PRINT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PRINT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PRINT_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION_TWEAK ${PRINT_VERSION_TWEAK})

set(CPACK_PACKAGE_VERSION ${PRINT_VERSION})

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "static C++ library for solving smth idk xD")


set(CPACK_RPM_PACKAGE_NAME "bubble_sore")
set(CPACK_RPM_PACKAGE_RELEASE 1)


set(CPACK_DEBIAN_PACKAGE_NAME "bubble_sort")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)


include(CPack)
