name: docker_test

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: hello-world
      run: |
        docker run -d -p 8888:80 prakhar1989/static-site
        mkdir artifacts && cd artifacts
        wget localhost:8888
        docker save -o ./test.tar prakhar1989/static-site
        
    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: artifacts/
        
