name: docker_test

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: hello-world
      run: |
        docker run hello-world
        mkdir artifacts && cd artifacts
        docker save -o ./hello-world.tar hello-world
        
    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: artifacts/
        
