name: CPack_solver_app

on:
   workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        cd lab_6
        cmake -H. -B_build -DCPACK_GENERATOR="TGZ"
        cmake --build _build --target package
        cd _build 
        cpack -G "DEB"
        cpack -G "RPM"
        mkdir ../artifacts
        mv *.tar.gz ../artifacts/
        mv *.deb ../artifacts/
        mv *.rpm ../artifacts/
           
    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: lab_6/artifact
        path: lab_6/artifacts/
